import { AppError } from '@/lib/errors';
import { OUTBOUND_TIMEOUT_MS } from '@/lib/limits';
import { logger } from '@/lib/logger';
import { parseCaptions, watchUrl, type TranscriptSegment } from './youtube';

/**
 * Transcript source layer.
 *
 * Two providers implement the same interface:
 *
 *  - `liveProvider`  — a real, unauthenticated YouTube caption fetch (InnerTube
 *    player endpoint, then a watch-page scrape as a fallback). No API key and no
 *    extra npm dependency. It genuinely works from residential IPs; YouTube
 *    frequently answers `LOGIN_REQUIRED` from datacenter/VPS ranges, in which
 *    case this provider FAILS LOUDLY instead of inventing content.
 *
 *  - `demoProvider` — a fixed, clearly-labelled sample transcript for trying the
 *    UI, the export formats and the downstream flow. It never claims to be the
 *    captions of the requested video.
 *
 * To add a real production source later (a caption API, a yt-dlp worker, a
 * proxy pool), implement `TranscriptProvider` and register it in `PROVIDERS`.
 * Nothing else in the app needs to change.
 */

export type TranscriptMode = 'live' | 'demo';

export interface TranscriptTrack {
  languageCode: string;
  label: string;
  autoGenerated: boolean;
}

export interface TranscriptResult {
  videoId: string;
  mode: TranscriptMode;
  /** True when the text is sample content rather than the video's captions. */
  isDemo: boolean;
  language: string;
  languageCode: string;
  autoGenerated: boolean;
  /** Every caption track the source reported, when it reported any. */
  availableTracks: TranscriptTrack[];
  segments: TranscriptSegment[];
  /** Human-readable provenance shown in the UI above the transcript. */
  provenance: string;
  title?: string;
  platform?: string;
  sourceUrl?: string;
  engine?: string;
}

export interface TranscriptProvider {
  id: TranscriptMode;
  label: string;
  description: string;
  fetchTranscript(videoId: string, languageHint?: string): Promise<TranscriptResult>;
}

const BROWSER_UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36';

async function fetchText(url: string, init: RequestInit = {}): Promise<{ ok: boolean; status: number; body: string }> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), OUTBOUND_TIMEOUT_MS);
  try {
    const response = await fetch(url, {
      ...init,
      signal: controller.signal,
      headers: {
        'user-agent': BROWSER_UA,
        'accept-language': 'en-US,en;q=0.9',
        ...(init.headers as Record<string, string> | undefined),
      },
      cache: 'no-store',
    });
    return { ok: response.ok, status: response.status, body: await response.text() };
  } catch (err) {
    if (err instanceof Error && err.name === 'AbortError') {
      throw new AppError('TIMEOUT', 'YouTube did not answer in time.', {
        hint: `The request was cancelled after ${Math.round(OUTBOUND_TIMEOUT_MS / 1000)}s. Try again.`,
      });
    }
    throw new AppError('UPSTREAM_BLOCKED', 'Could not reach YouTube from this server.', {
      hint: err instanceof Error ? err.message : 'Check the server network connection.',
    });
  } finally {
    clearTimeout(timer);
  }
}

/* ------------------------------------------------------------------ *
 * Live provider
 * ------------------------------------------------------------------ */

interface RawCaptionTrack {
  baseUrl: string;
  languageCode: string;
  name: string;
  kind?: string;
}

const INNERTUBE_KEY = 'AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8';

/**
 * InnerTube clients worth trying, cheapest/most-permissive first. YouTube
 * rotates which ones serve anonymous requests, so we try several rather than
 * betting the module on one.
 */
const INNERTUBE_CLIENTS = [
  { clientName: 'ANDROID', clientVersion: '19.09.37', androidSdkVersion: 30 },
  { clientName: 'WEB', clientVersion: '2.20240304.00.00' },
  { clientName: 'MWEB', clientVersion: '2.20240304.00.00' },
  { clientName: 'TVHTML5_SIMPLY_EMBEDDED_PLAYER', clientVersion: '2.0' },
] as const;

interface PlayerProbe {
  tracks: RawCaptionTrack[];
  title?: string;
  /** Reason the attempt produced nothing, for honest error reporting. */
  reason?: string;
}

function readTracks(payload: unknown): RawCaptionTrack[] {
  const renderer = (payload as { captions?: { playerCaptionsTracklistRenderer?: { captionTracks?: unknown } } })
    ?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  if (!Array.isArray(renderer)) return [];
  return renderer
    .map((raw) => {
      const t = raw as { baseUrl?: string; languageCode?: string; kind?: string; name?: { simpleText?: string; runs?: { text: string }[] } };
      const label = t.name?.simpleText ?? t.name?.runs?.map((r) => r.text).join('') ?? t.languageCode ?? 'Unknown';
      return { baseUrl: t.baseUrl ?? '', languageCode: t.languageCode ?? 'unknown', name: label, kind: t.kind };
    })
    .filter((t) => t.baseUrl !== '');
}

async function probeInnertube(videoId: string): Promise<PlayerProbe> {
  const reasons: string[] = [];
  for (const client of INNERTUBE_CLIENTS) {
    const body = JSON.stringify({
      context: { client: { ...client, hl: 'en', gl: 'US' } },
      videoId,
      contentCheckOk: true,
      racyCheckOk: true,
    });
    const { body: text } = await fetchText(`https://www.youtube.com/youtubei/v1/player?key=${INNERTUBE_KEY}`, {
      method: 'POST',
      body,
      headers: { 'content-type': 'application/json' },
    });
    let payload: unknown;
    try {
      payload = JSON.parse(text);
    } catch {
      reasons.push(`${client.clientName}: response was not JSON`);
      continue;
    }
    const status = (payload as { playabilityStatus?: { status?: string; reason?: string } }).playabilityStatus;
    const tracks = readTracks(payload);
    if (tracks.length > 0) {
      const title = (payload as { videoDetails?: { title?: string } }).videoDetails?.title;
      return { tracks, title };
    }
    reasons.push(`${client.clientName}: ${status?.status ?? 'no captions'}${status?.reason ? ` (${status.reason})` : ''}`);
  }
  return { tracks: [], reason: reasons.join('; ') };
}

async function probeWatchPage(videoId: string): Promise<PlayerProbe> {
  const { body } = await fetchText(watchUrl(videoId));
  const match = /"captionTracks":(\[.*?\])(?=,")/s.exec(body);
  if (!match) {
    const blocked = /Sign in to confirm|consent\.youtube\.com|not a bot/i.test(body);
    return { tracks: [], reason: blocked ? 'watch page: YouTube asked this server to sign in' : 'watch page: no caption track list present' };
  }
  try {
    return { tracks: readTracks({ captions: { playerCaptionsTracklistRenderer: { captionTracks: JSON.parse(match[1]!) } } }) };
  } catch {
    return { tracks: [], reason: 'watch page: caption track list could not be parsed' };
  }
}

function pickTrack(tracks: RawCaptionTrack[], languageHint?: string): RawCaptionTrack {
  if (languageHint) {
    const exact = tracks.find((t) => t.languageCode.toLowerCase() === languageHint.toLowerCase());
    if (exact) return exact;
    const prefix = tracks.find((t) => t.languageCode.toLowerCase().startsWith(languageHint.slice(0, 2).toLowerCase()));
    if (prefix) return prefix;
  }
  const manualEnglish = tracks.find((t) => t.languageCode.startsWith('en') && t.kind !== 'asr');
  if (manualEnglish) return manualEnglish;
  const anyEnglish = tracks.find((t) => t.languageCode.startsWith('en'));
  if (anyEnglish) return anyEnglish;
  const anyManual = tracks.find((t) => t.kind !== 'asr');
  return anyManual ?? tracks[0]!;
}

export const liveProvider: TranscriptProvider = {
  id: 'live',
  label: 'Live fetch',
  description:
    'Requests the real caption track straight from YouTube with no API key. Works when YouTube serves this server anonymously.',

  async fetchTranscript(videoId, languageHint) {
    let probe = await probeInnertube(videoId);
    if (probe.tracks.length === 0) {
      const fallback = await probeWatchPage(videoId);
      probe = fallback.tracks.length > 0 ? fallback : { tracks: [], reason: [probe.reason, fallback.reason].filter(Boolean).join(' | ') };
    }

    if (probe.tracks.length === 0) {
      logger.warn('transcript.live_unavailable', { videoId, reason: probe.reason });
      throw new AppError('UPSTREAM_BLOCKED', 'YouTube did not return a caption track for this video.', {
        hint:
          `Upstream said: ${probe.reason || 'no detail given'}. ` +
          'Either the video genuinely has no captions, or YouTube is refusing anonymous requests from this server ' +
          '(common on VPS/datacenter IPs). Switch to Demo mode to exercise the exports, or paste a caption file below.',
      });
    }

    const track = pickTrack(probe.tracks, languageHint);
    // json3 is the most reliable modern format; fall back to the default XML.
    const attempts = [`${track.baseUrl}&fmt=json3`, track.baseUrl];
    for (const url of attempts) {
      const { body } = await fetchText(url);
      const { segments } = parseCaptions(body);
      if (segments.length > 0) {
        return {
          videoId,
          mode: 'live',
          isDemo: false,
          language: track.name,
          languageCode: track.languageCode,
          autoGenerated: track.kind === 'asr',
          availableTracks: probe.tracks.map((t) => ({
            languageCode: t.languageCode,
            label: t.name,
            autoGenerated: t.kind === 'asr',
          })),
          segments,
          title: probe.title,
          provenance: `Fetched live from YouTube — track "${track.name}" (${track.languageCode}${track.kind === 'asr' ? ', auto-generated' : ''}).`,
        };
      }
    }

    throw new AppError('UPSTREAM_BLOCKED', 'YouTube listed a caption track but returned no text for it.', {
      hint: 'This usually means the track was withdrawn between the two requests. Try again in a moment.',
    });
  },
};

/* ------------------------------------------------------------------ *
 * Demo provider
 * ------------------------------------------------------------------ */

/**
 * Sample content. Written so that it is impossible to mistake for the real
 * captions of whatever video the user pasted — the text says what it is.
 */
const DEMO_LINES: [number, number, string][] = [
  [0, 4.2, 'This is sample transcript content from the Unified Utility Platform demo provider.'],
  [4.2, 5.1, 'It is not the caption track of the video you pasted, and it never will be.'],
  [9.3, 4.6, 'Demo mode exists so you can try the viewer, the timestamp toggle and every export format.'],
  [13.9, 5.4, 'The exports below are produced by the same code paths that a real transcript would use.'],
  [19.3, 5.0, 'Live mode talks to YouTube directly and needs no API key or extra dependency.'],
  [24.3, 6.2, 'YouTube often refuses anonymous caption requests from datacenter and VPS addresses.'],
  [30.5, 4.9, 'When that happens, live mode reports the refusal instead of inventing a transcript.'],
  [35.4, 5.7, 'To wire in a production source, implement TranscriptProvider in src/modules/transcript/providers.ts.'],
  [41.1, 4.3, 'You can also paste a real .srt, .vtt or timedtext file into the parser on this page.'],
  [45.4, 4.0, 'That path is fully real: parsing, timestamps and exports all run locally in your browser.'],
];

export const demoProvider: TranscriptProvider = {
  id: 'demo',
  label: 'Demo transcript',
  description: 'Fixed sample content for exercising the viewer and the export formats. Not the real captions.',

  async fetchTranscript(videoId) {
    return {
      videoId,
      mode: 'demo',
      isDemo: true,
      language: 'English (sample)',
      languageCode: 'en',
      autoGenerated: false,
      availableTracks: [],
      segments: DEMO_LINES.map(([start, duration, text]) => ({ start, duration, text })),
      provenance: 'DEMO CONTENT — fixed sample text, not the captions of this video.',
    };
  },
};

export const PROVIDERS: Record<TranscriptMode, TranscriptProvider> = {
  live: liveProvider,
  demo: demoProvider,
};

export function describeProviders() {
  return (Object.keys(PROVIDERS) as TranscriptMode[]).map((id) => ({
    id,
    label: PROVIDERS[id].label,
    description: PROVIDERS[id].description,
    returnsRealCaptions: id === 'live',
  }));
}
