'use client';

import { useMemo, useState } from 'react';
import Banner from '@/components/Banner';

type TranscriptResponse = {
  videoId: string;
  mode: 'live' | 'demo';
  isDemo: boolean;
  title?: string;
  provenance: string;
  language: string;
  languageCode: string;
  autoGenerated: boolean;
  availableTracks: { languageCode: string; label: string; autoGenerated: boolean }[];
  segments: { start: number; duration: number; text: string }[];
  plainText: string;
  srt: string;
  json: string;
  platform?: string;
  sourceUrl?: string;
  engine?: string;
};

function download(name: string, mime: string, text: string) {
  const blob = new Blob([text], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  a.click();
  URL.revokeObjectURL(url);
}

export default function TranscriptClient() {
  const [url, setUrl] = useState('https://www.youtube.com/watch?v=dQw4w9WgXcQ');
  const [mode, setMode] = useState<'live' | 'demo'>('live');
  const [language, setLanguage] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [hint, setHint] = useState<string | null>(null);
  const [result, setResult] = useState<TranscriptResponse | null>(null);

  const filenameBase = useMemo(() => (result?.title || result?.videoId || 'transcript').replace(/[^\w.-]+/g, '_'), [result]);

  async function onSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setLoading(true);
    setError(null);
    setHint(null);
    setResult(null);
    try {
      const response = await fetch('/api/transcript', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ url, mode, languageHint: language }),
      });
      const data = await response.json();
      if (!response.ok) {
        setError(data.error?.message || 'Request failed.');
        setHint(data.error?.hint || null);
        return;
      }
      setResult(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Request failed.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="card">
      <h1>Video Transcript</h1>
      <p className="lede">Paste a public video URL from YouTube, Instagram, TikTok, or X/Twitter. This tool transcribes the audio directly for more consistent cross-platform results.</p>

      <Banner tone="info" title="How this works">
        <div className="hint">
          Live mode downloads the public media, extracts audio, and transcribes it. It is slower than caption fetch and may fail on private, blocked, or login-required posts. Demo mode still exists to test the viewer/export flow.
        </div>
      </Banner>

      <form onSubmit={onSubmit}>
        <div className="field">
          <label htmlFor="video-url">Public video URL</label>
          <input id="video-url" type="url" value={url} onChange={(e) => setUrl(e.target.value)} required />
          <p className="hint">Supported now: YouTube, Instagram, TikTok, X/Twitter public video URLs.</p>
        </div>
        <div className="field">
          <label htmlFor="mode">Mode</label>
          <select id="mode" value={mode} onChange={(e) => setMode(e.target.value as 'live' | 'demo')}>
            <option value="live">Live transcription</option>
            <option value="demo">Demo transcript</option>
          </select>
        </div>
        <div className="field">
          <label htmlFor="lang">Language hint (optional)</label>
          <input id="lang" type="text" value={language} onChange={(e) => setLanguage(e.target.value)} placeholder="en, id, en-US" />
        </div>
        <button type="submit" disabled={loading}>{loading ? 'Transcribing…' : 'Get transcript'}</button>
      </form>

      {error ? <Banner tone="error" title={error}>{hint ? <div className="hint">{hint}</div> : null}</Banner> : null}

      {result ? (
        <div className="card" style={{ marginTop: '1rem' }}>
          <h2>{result.title || `Source ${result.videoId}`}</h2>
          <p className="muted small">{result.provenance}</p>
          <ul>
            <li><strong>Mode:</strong> {result.mode}{result.isDemo ? ' (sample transcript)' : ''}</li>
            {result.platform ? <li><strong>Platform:</strong> {result.platform}</li> : null}
            <li><strong>Language:</strong> {result.language} ({result.languageCode})</li>
            {result.engine ? <li><strong>Engine:</strong> {result.engine}</li> : null}
            <li><strong>Segments:</strong> {result.segments.length}</li>
          </ul>
          <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
            <button type="button" onClick={() => navigator.clipboard.writeText(result.plainText)}>Copy text</button>
            <button type="button" onClick={() => download(`${filenameBase}.txt`, 'text/plain;charset=utf-8', result.plainText)}>Download TXT</button>
            <button type="button" onClick={() => download(`${filenameBase}.srt`, 'application/x-subrip', result.srt)}>Download SRT</button>
            <button type="button" onClick={() => download(`${filenameBase}.json`, 'application/json', result.json)}>Download JSON</button>
          </div>
          <h3>Transcript</h3>
          <textarea readOnly rows={18} value={result.segments.map((s) => `${Math.floor(s.start / 60)}:${String(Math.floor(s.start % 60)).padStart(2, '0')}  ${s.text}`).join('\n')} />
        </div>
      ) : null}
    </div>
  );
}
