'use client';

import { useMemo, useState } from 'react';
import Banner from '@/components/Banner';

type TranscriptResponse = {
  videoId: string;
  mode: 'live' | 'demo';
  isDemo: boolean;
  title?: string;
  provenance: string;
  language: string;
  languageCode: string;
  autoGenerated: boolean;
  availableTracks: { languageCode: string; label: string; autoGenerated: boolean }[];
  segments: { start: number; duration: number; text: string }[];
  plainText: string;
  srt: string;
  json: string;
};

function download(name: string, mime: string, text: string) {
  const blob = new Blob([text], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  a.click();
  URL.revokeObjectURL(url);
}

export default function TranscriptClient() {
  const [url, setUrl] = useState('https://www.youtube.com/watch?v=dQw4w9WgXcQ');
  const [mode, setMode] = useState<'live' | 'demo'>('live');
  const [language, setLanguage] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [hint, setHint] = useState<string | null>(null);
  const [result, setResult] = useState<TranscriptResponse | null>(null);

  const filenameBase = useMemo(() => (result?.title || result?.videoId || 'transcript').replace(/[^\w.-]+/g, '_'), [result]);

  async function onSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setLoading(true);
    setError(null);
    setHint(null);
    setResult(null);
    try {
      const response = await fetch('/api/transcript', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ url, mode, languageHint: language }),
      });
      const data = await response.json();
      if (!response.ok) {
        setError(data.error?.message || 'Request failed.');
        setHint(data.error?.hint || null);
        return;
      }
      setResult(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Request failed.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="card">
      <h1>YouTube Transcript</h1>
      <p className="lede">Fetch real captions when YouTube serves them anonymously from this server, or switch to demo mode to test the UI and exports without pretending the transcript is real.</p>

      <form onSubmit={onSubmit}>
        <div className="field">
          <label htmlFor="yt-url">YouTube URL or video ID</label>
          <input id="yt-url" type="url" value={url} onChange={(e) => setUrl(e.target.value)} required />
        </div>
        <div className="field">
          <label htmlFor="mode">Mode</label>
          <select id="mode" value={mode} onChange={(e) => setMode(e.target.value as 'live' | 'demo')}>
            <option value="live">Live fetch</option>
            <option value="demo">Demo transcript</option>
          </select>
          <p className="hint">Live mode tries to fetch real captions. Demo mode returns sample content and says so clearly.</p>
        </div>
        <div className="field">
          <label htmlFor="lang">Language hint (optional)</label>
          <input id="lang" type="text" value={language} onChange={(e) => setLanguage(e.target.value)} placeholder="en, id, en-US" />
        </div>
        <button type="submit" disabled={loading}>{loading ? 'Fetching…' : 'Get transcript'}</button>
      </form>

      {error ? <Banner tone="error" title={error}>{hint ? <div className="hint">{hint}</div> : null}</Banner> : null}

      {result ? (
        <div className="card" style={{ marginTop: '1rem' }}>
          <h2>{result.title || `Video ${result.videoId}`}</h2>
          <p className="muted small">{result.provenance}</p>
          <ul>
            <li><strong>Mode:</strong> {result.mode}{result.isDemo ? ' (sample transcript)' : ''}</li>
            <li><strong>Language:</strong> {result.language} ({result.languageCode})</li>
            <li><strong>Track type:</strong> {result.autoGenerated ? 'Auto-generated' : 'Manual / standard'}</li>
            <li><strong>Segments:</strong> {result.segments.length}</li>
          </ul>
          <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
            <button type="button" onClick={() => navigator.clipboard.writeText(result.plainText)}>Copy text</button>
            <button type="button" onClick={() => download(`${filenameBase}.txt`, 'text/plain;charset=utf-8', result.plainText)}>Download TXT</button>
            <button type="button" onClick={() => download(`${filenameBase}.srt`, 'application/x-subrip', result.srt)}>Download SRT</button>
            <button type="button" onClick={() => download(`${filenameBase}.json`, 'application/json', result.json)}>Download JSON</button>
          </div>
          {result.availableTracks.length ? (
            <>
              <h3>Available tracks</h3>
              <ul>
                {result.availableTracks.map((track) => (
                  <li key={`${track.languageCode}-${track.label}`}>{track.label} ({track.languageCode}){track.autoGenerated ? ' · auto' : ''}</li>
                ))}
              </ul>
            </>
          ) : null}
          <h3>Transcript</h3>
          <textarea readOnly rows={18} value={result.segments.map((s) => `${Math.floor(s.start / 60)}:${String(Math.floor(s.start % 60)).padStart(2, '0')}  ${s.text}`).join('\n')} />
        </div>
      ) : null}
    </div>
  );
}
