'use client';

import { useMemo, useState } from 'react';
import Banner from '@/components/Banner';
import DownloadPanel from '@/components/downloader/DownloadPanel';
import { useDownloader } from '@/components/downloader/useDownloader';

type TranscriptResponse = {
  videoId: string;
  mode: 'live' | 'demo';
  isDemo: boolean;
  title?: string;
  provenance: string;
  language: string;
  languageCode: string;
  autoGenerated: boolean;
  availableTracks: { languageCode: string; label: string; autoGenerated: boolean }[];
  segments: { start: number; duration: number; text: string }[];
  plainText: string;
  srt: string;
  json: string;
  platform?: string;
  sourceUrl?: string;
  engine?: string;
};

function downloadText(name: string, mime: string, text: string) {
  const blob = new Blob([text], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  a.click();
  URL.revokeObjectURL(url);
}

export default function TranscriptClient() {
  const [url, setUrl] = useState('https://www.youtube.com/watch?v=dQw4w9WgXcQ');
  const [mode, setMode] = useState<'live' | 'demo'>('live');
  const [language, setLanguage] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [hint, setHint] = useState<string | null>(null);
  const [result, setResult] = useState<TranscriptResponse | null>(null);
  const [activeTab, setActiveTab] = useState<'transcript' | 'download'>('download');
  const downloader = useDownloader();

  const filenameBase = useMemo(
    () => (result?.title || result?.videoId || 'transcript').replace(/[^\w.-]+/g, '_'),
    [result],
  );

  async function runTranscript() {
    if (!url.trim()) return;
    setActiveTab('transcript');
    setLoading(true);
    setError(null);
    setHint(null);
    setResult(null);
    try {
      const response = await fetch('/api/transcript', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ url, mode, languageHint: language }),
      });
      const data = await response.json();
      if (!response.ok) {
        setError(data.error?.message || 'Request failed.');
        setHint(data.error?.hint || null);
        return;
      }
      setResult(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Request failed.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="card tool-shell">
      <h1>Video Transcript</h1>
      <p className="lede">Paste link, lalu pilih mau ambil transcript atau langsung download video.</p>

      <div className="field">
        <label htmlFor="video-url">Public video URL</label>
        <input id="video-url" type="url" value={url} onChange={(e) => setUrl(e.target.value)} required />
        <p className="hint">Supported now: YouTube, Instagram, TikTok, X/Twitter public video URLs.</p>
      </div>

      <div className="button-row">
        <button
          type="button"
          className={activeTab === 'transcript' ? 'primary' : ''}
          disabled={loading}
          onClick={() => void runTranscript()}
        >
          {loading ? 'Processing…' : 'Get transcript'}
        </button>
        <button
          type="button"
          className={activeTab === 'download' ? 'primary' : ''}
          onClick={() => setActiveTab('download')}
        >
          Download video
        </button>
      </div>

      <details className="card" style={{ marginTop: '1rem' }}>
        <summary><strong>Advanced transcript options</strong></summary>
        <div className="field" style={{ marginTop: '1rem' }}>
          <label htmlFor="mode">Mode</label>
          <select id="mode" value={mode} onChange={(e) => setMode(e.target.value as 'live' | 'demo')}>
            <option value="live">Live transcription</option>
            <option value="demo">Demo transcript</option>
          </select>
        </div>
        <div className="field">
          <label htmlFor="lang">Language hint (optional)</label>
          <input id="lang" type="text" value={language} onChange={(e) => setLanguage(e.target.value)} placeholder="en, id, en-US" />
        </div>
      </details>

      {activeTab === 'transcript' && error ? (
        <Banner tone="error" title={error}>
          {hint ? <div className="hint">{hint}</div> : null}
        </Banner>
      ) : null}

      {activeTab === 'download' ? <DownloadPanel url={url} downloader={downloader} showEngineBanner={false} /> : null}

      {result ? (
        <div className="card" style={{ marginTop: '1rem' }}>
          <h2>{result.title || `Source ${result.videoId}`}</h2>
          <p className="muted small">{result.provenance}</p>
          <ul>
            <li><strong>Mode:</strong> {result.mode}{result.isDemo ? ' (sample transcript)' : ''}</li>
            {result.platform ? <li><strong>Platform:</strong> {result.platform}</li> : null}
            <li><strong>Language:</strong> {result.language} ({result.languageCode})</li>
            {result.engine ? <li><strong>Engine:</strong> {result.engine}</li> : null}
            <li><strong>Segments:</strong> {result.segments.length}</li>
          </ul>
          <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
            <button type="button" onClick={() => navigator.clipboard.writeText(result.plainText)}>Copy text</button>
            <button type="button" onClick={() => downloadText(`${filenameBase}.txt`, 'text/plain;charset=utf-8', result.plainText)}>Download TXT</button>
            <button type="button" onClick={() => downloadText(`${filenameBase}.srt`, 'application/x-subrip', result.srt)}>Download SRT</button>
            <button type="button" onClick={() => downloadText(`${filenameBase}.json`, 'application/json', result.json)}>Download JSON</button>
          </div>
          <h3>Transcript</h3>
          <textarea readOnly rows={18} value={result.segments.map((s) => `${Math.floor(s.start / 60)}:${String(Math.floor(s.start % 60)).padStart(2, '0')}  ${s.text}`).join('\n')} />
        </div>
      ) : null}
    </div>
  );
}
