import { json, errorResponse } from '@/lib/http';
import { enforceRateLimit, RULES } from '@/lib/ratelimit';
import { parseHttpUrl, requireOneOf, requireString } from '@/lib/validate';
import { transcribeAudio, fetchTranscriptSource } from '@/modules/transcript/asr';
import { PROVIDERS } from '@/modules/transcript/providers';
import { toJson, toPlainText, toSrt, type TranscriptSegment } from '@/modules/transcript/youtube';

function transcriptIdFromUrl(url: string) {
  return Buffer.from(url).toString('base64url').slice(0, 16) || 'transcript';
}

export async function GET() {
  return json({
    modes: [
      { id: 'live', label: 'Live transcription' },
      { id: 'demo', label: 'Demo transcript' },
    ],
    supportedPlatforms: ['YouTube', 'Instagram', 'TikTok', 'X / Twitter'],
  });
}

export async function POST(req: Request) {
  try {
    enforceRateLimit(req, RULES.transcript);
    const body = await req.json();
    const rawUrl = requireString(body.url, 'a public video URL', { maxLength: 1000 });
    const mode = requireOneOf(body.mode ?? 'live', ['live', 'demo'] as const, 'mode');
    const languageHint = typeof body.languageHint === 'string' ? body.languageHint.trim() : '';

    if (mode === 'demo') {
      const demoId = transcriptIdFromUrl(rawUrl);
      const demo = await PROVIDERS.demo.fetchTranscript(demoId, languageHint || undefined);
      return json({
        ...demo,
        platform: 'Demo',
        sourceUrl: rawUrl,
        engine: 'demo',
        plainText: toPlainText(demo.segments, { timestamps: false }),
        srt: toSrt(demo.segments),
        json: toJson(demo.segments, { videoId: demo.videoId, title: demo.title, language: demo.languageCode, mode: demo.mode, platform: 'Demo' }),
      });
    }

    const parsed = parseHttpUrl(rawUrl, 'public video URL');
    const source = await fetchTranscriptSource(parsed.toString());
    const asr = await transcribeAudio(source.audioBytes, source.audioFilename, languageHint || undefined);
    const segments = asr.segments as TranscriptSegment[];
    const transcriptId = source.detection.mediaId || transcriptIdFromUrl(source.canonicalUrl);

    return json({
      videoId: transcriptId,
      mode: 'live',
      isDemo: false,
      title: source.title,
      platform: source.platform,
      sourceUrl: source.canonicalUrl,
      provenance: `${source.provenance.join(' ')} Transcribed locally with faster-whisper model ${asr.model}.`,
      language: asr.language,
      languageCode: asr.language,
      autoGenerated: false,
      availableTracks: [],
      engine: `faster-whisper:${asr.model}`,
      segments,
      plainText: toPlainText(segments, { timestamps: false }),
      srt: toSrt(segments),
      json: toJson(segments, {
        videoId: transcriptId,
        title: source.title,
        language: asr.language,
        mode: 'live',
        platform: source.platform,
        sourceUrl: source.canonicalUrl,
        engine: `faster-whisper:${asr.model}`,
      }),
    });
  } catch (err) {
    return errorResponse('api.transcript', err);
  }
}
