import { json, errorResponse } from '@/lib/http';
import { enforceRateLimit, RULES } from '@/lib/ratelimit';
import { parseHttpUrl, requireOneOf, requireString } from '@/lib/validate';
import { PROVIDERS } from '@/modules/transcript/providers';
import { toJson, toPlainText, toSrt } from '@/modules/transcript/youtube';
import { routeTranscript, providerReport } from '@/modules/providers/router';
import { detectPlatform } from '@/modules/downloader/platforms';

function transcriptIdFromUrl(url: string) {
  return Buffer.from(url).toString('base64url').slice(0, 16) || 'transcript';
}

export async function GET() {
  return json({
    modes: [
      { id: 'live', label: 'Live transcription' },
      { id: 'demo', label: 'Demo transcript' },
    ],
    supportedPlatforms: ['YouTube', 'Instagram', 'TikTok', 'X / Twitter'],
    providers: providerReport(),
  });
}

export async function POST(req: Request) {
  try {
    enforceRateLimit(req, RULES.transcript);
    const body = await req.json();
    const rawUrl = requireString(body.url, 'a public video URL', { maxLength: 1000 });
    const mode = requireOneOf(body.mode ?? 'live', ['live', 'demo'] as const, 'mode');
    const languageHint = typeof body.languageHint === 'string' ? body.languageHint.trim() : '';

    if (mode === 'demo') {
      const demoId = transcriptIdFromUrl(rawUrl);
      const demo = await PROVIDERS.demo.fetchTranscript(demoId, languageHint || undefined);
      return json({
        ...demo,
        platform: 'Demo',
        sourceUrl: rawUrl,
        engine: 'demo',
        providerSource: 'demo',
        providerAttempts: [],
        providers: providerReport(),
        plainText: toPlainText(demo.segments, { timestamps: false }),
        srt: toSrt(demo.segments),
        json: toJson(demo.segments, {
          videoId: demo.videoId,
          title: demo.title,
          language: demo.languageCode,
          mode: demo.mode,
          platform: 'Demo',
        }),
      });
    }

    const parsed = parseHttpUrl(rawUrl, 'public video URL');
    const detection = detectPlatform(parsed);
    if (!detection.matched) {
      throw new Error(detection.reason);
    }

    const routed = await routeTranscript(parsed.toString(), detection, {
      languageHint: languageHint || undefined,
    });
    const segments = routed.value.segments;
    const transcriptId = detection.mediaId || transcriptIdFromUrl(routed.value.sourceUrl);

    return json({
      videoId: transcriptId,
      mode: 'live',
      isDemo: false,
      title: routed.value.title,
      platform: routed.value.platform,
      sourceUrl: routed.value.sourceUrl,
      provenance: routed.value.provenance.join(' '),
      language: routed.value.language,
      languageCode: routed.value.language,
      autoGenerated: false,
      availableTracks: [],
      engine: routed.value.engine,
      providerSource: routed.provider,
      providerAttempts: routed.attempts,
      providers: providerReport(),
      segments,
      plainText: toPlainText(segments, { timestamps: false }),
      srt: toSrt(segments),
      json: toJson(segments, {
        videoId: transcriptId,
        title: routed.value.title,
        language: routed.value.language,
        mode: 'live',
        platform: routed.value.platform,
        sourceUrl: routed.value.sourceUrl,
        engine: routed.value.engine,
        providerSource: routed.provider,
      }),
    });
  } catch (err) {
    if (err instanceof Error && !('code' in err)) {
      return Response.json({ error: { code: 'INVALID_INPUT', message: err.message } }, { status: 400 });
    }
    return errorResponse('api.transcript', err);
  }
}
